[package]
name = "private-code-providers"
version = "0.1.0"
edition = "2024"

[dependencies]
private-code-protocol.workspace = true
tokio.workspace = true
reqwest.workspace = true
eventsource-stream.workspace = true
futures-util.workspace = true
keyring.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
async-trait.workspace = true

